#!/bin/bash
COUNT=$(ls -1 $1 | wc -l)
ITER=0

echo $1
echo $COUNT


for file in $2/*; do 
   if [ -f "$file" ]; then 
     ITER=$(($ITER + 1))
     echo "![$(basename $file)](/$(basename $1)/$(basename $file))" >> ./"$2".md
      echo "$ITER/$COUNT"
      #echo "$(basename $file)"

    fi 
done
